/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package log.parser;
import log.parser.model.LogEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        if (args.length != 1) {
            logger.error("Required log file path missing");
            return;
        }
        String filePath = args[0];
        File logFile = new File(filePath);
        if (!logFile.exists()){
            logger.info("Working Directory = " + System.getProperty("user.dir"));
            logger.error(filePath + " does not exist. Quitting...");
            return;
        }

        LogEventWriter eventWriter = new LogEventWriter(logger);
        eventWriter.init();
        LogEventProcessor processor = new LogEventProcessor(eventWriter, logger);
        try (Scanner scanner = new Scanner(logFile)) {
            while (scanner.hasNext()) {
                String currentLine = scanner.nextLine();
                LogEvent evt = LogEventParser.parseEvent(currentLine);
                processor.Process(evt);
            }
        } catch (IOException e) {
            logger.error("Unable to process input file", e);
            e.printStackTrace();
        }
        catch (Exception ge){
            logger.error("Ooops, something went wrong", ge);
            ge.printStackTrace();
        }
        finally {
            eventWriter.cleanup();
            logger.info(eventWriter.getInsertCount() + " rows inserted into DB");
        }
    }


}
